# Generated by Django 3.1.4 on 2020-12-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201208_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookonuser',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='bookonuser',
            name='lname',
        ),
    ]
