# Generated by Django 3.1.4 on 2021-05-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210503_1739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnerMore',
        ),
    ]
