# Generated by Django 3.2.1 on 2021-05-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_ownermore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookonuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='bookonuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bookonuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
