# Generated by Django 3.1.4 on 2020-12-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20201208_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='shop_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='shop_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
