# Generated by Django 3.1.4 on 2021-03-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20201218_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='average_service_time',
            field=models.IntegerField(),
        ),
    ]
