# Generated by Django 3.1.4 on 2021-03-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20210307_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='average_service_time',
            field=models.DurationField(),
        ),
    ]
