# Generated by Django 3.1.4 on 2021-05-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20210503_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='end_time',
            new_name='close_time',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='start_time',
            new_name='open_time',
        ),
    ]
