# Generated by Django 3.1.4 on 2021-05-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20210504_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
